RMS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("restaraunt.urls")),
    path("admin/", admin.site.urls),
]

restaraunt/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView



from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    path("menu", views.menu, name="menu"),
    path("contactus", views.contactus, name="contactus"),
    path('login/', views.login_view, name='login'),
    path('signup/', views.register, name='register'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]
#     # Tables
urlpatterns += [
    path('booking/', views.BookingListView.as_view(), name='booking_list'),
    path('booking_create/', views.BookingCreateView.as_view(), name='booking_create'),

    path('booking/delete/<int:pk>/', views.BookingDeleteView.as_view(), name='booking_delete'),
]  

restaraunt/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
import datetime
from django.utils import timezone


class Table(models.Model):
    TABLE_STATUS = (
        ("Available", "Available"),
        ("Out of Service", "Out of Service"),

    )
    Name = models.CharField(max_length=200, unique=True)
    Capacity = models.IntegerField(blank=False, null=False)
    status = models.CharField(max_length=15,
                              choices=TABLE_STATUS,
                              default="Available", )

    def __str__(self):
        return f'{self.Name}'


class Booking(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    time = models.TimeField()
    date = models.DateField(null=False, blank=False)
    person = models.IntegerField(null=False, blank=False)
    table = models.ForeignKey(Table, null=False, blank=False, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        self.validate_date_time()
        self.assign_table()
        super().save(*args, **kwargs)

    @property
    def datetime(self,*args,**kwargs):
        return datetime.datetime.combine(self.date, self.time)

    def validate_date_time(self):
        current_datetime = datetime.datetime.now()
        if self.datetime < current_datetime:
            raise ValidationError("Invalid Date & Time.")

    def assign_table(self):
        available_tables = Table.objects.filter(status='Available').order_by('Capacity')
        for table in available_tables:
            if table.Capacity >= self.person:
                booking_start_time = self.datetime - timezone.timedelta(hours=1)
                booking_end_time = self.datetime + timezone.timedelta(hours=1)
                # error here
                existing_bookings = Booking.objects.filter(
                    table=table,
                    date=self.date,
                    time__gte=datetime.datetime.combine(self.date, self.time) - datetime.timedelta(hours=1),
                    time__lt=datetime.datetime.combine(self.date, self.time) + datetime.timedelta(hours=1)
                ).exclude(pk=self.pk)

                if not existing_bookings:
                    self.table = table
                    break
        else:
            raise ValidationError("No available table found at the specified time")

restaraunt/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from collections import OrderedDict
from .models import Booking
from datetime import date
from datetime import datetime,timedelta

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100 ,  widget= forms.TextInput(attrs={"class":"mb_30"}))
    password = forms.CharField(widget= forms.PasswordInput(attrs={"class":"mb_30"}))

class RegisterForm(UserCreationForm):
    class Meta:
        model=get_user_model()
        fields = ['username','email','password1','password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Add classes to specific fields
        self.fields['username'].widget.attrs['class'] = 'mb_20'
        self.fields['email'].widget.attrs['class'] = 'mb_20'
        self.fields['password1'].widget.attrs['class'] = 'mb_20'
        self.fields['password2'].widget.attrs['class'] = 'mb_20'
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields= '__all__'
        exclude=['owner','table']
        widgets={
            'date':forms.DateInput(attrs={'type':'date', 'min': date.today().strftime('%Y-%m-%d'),'class':'form-control mb_15'}),
            # 'time':forms.TimeInput(attrs={'type':'time','min': (datetime.now() - timedelta(minutes=5)).strftime('%H:%M')})
            'time':forms.TimeInput(attrs={'type':'time','class':'form-control mb_15'})
        }

restaraunt/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from .forms import LoginForm,RegisterForm, BookingForm
from django.core.exceptions import ValidationError
# , BookingForm
from django.http import HttpResponseBadRequest
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Booking
from .mixins import AdminRequiredMixin,UserorAdminRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

def index(request):
        if request.user.is_authenticated and request.user.is_superuser:
            return redirect('booking_list')
        elif request.user.is_authenticated:
            return redirect('booking_list')
            
        error = request.GET.get("errors")

        context = {"form":LoginForm(),"register":RegisterForm(),"errors":error}

        return render(request, "restaraunt/index.html", context)


def menu(request):
    menu_items=[
        {"name":"menu2_img_1.jpg","category":"Biryani","title":"Hyderabadi","price":"$65.00"},
        {"name":"menu2_img_2.jpg","category":"Chicken","title":"Daria Shevtsova","price":"$80.00"},
        {"name":"menu2_img_3.jpg","category":"Burger","title":"Spicy Burger","price":"$100.00"},
        {"name":"menu2_img_4.jpg","category":"Dessert","title":"Fried Chicken","price":"$99.00"},
        {"name":"menu2_img_5.jpg","category":"kabab","title":"Mozzarella Sticks","price":"$75.00"},
        {"name":"menu2_img_6.jpg","category":"kacchi","title":"Popcorn Chicken","price":"$65.00"},
        {"name":"menu2_img_7.jpg","category":"noodles","title":"Chicken Wings","price":"$79.00"},
        {"name":"menu2_img_8.jpg","category":"grill","title":"Onion Rings","price":"$110.00"},
        
        ]
    context = {"items":menu_items
    }
    return render(request, "restaraunt/menu.html", context)

def contactus(request):

    return render(request, "restaraunt/contact.html",)



def login_view(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                error_message = 'Invalid login credentials'
                return redirect('/'+ f'?errors={error_message}')
    else:
        return redirect('index')


def register(request):
    if request.method == 'GET':
        return redirect('index')
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        return render(request, 'restaraunt/index.html',{'register':RegisterForm(),'errors':form.errors,'form':LoginForm()})
    else:
        register = RegisterForm()
        form = LoginForm()
    return render(request, 'restaraunt/index.html', {'register': RegisterForm(),'form':LoginForm()})

def logout_view(request):
    if request.method=="POST":
        logout(request)
        return redirect('index')
    

class BookingListView(LoginRequiredMixin,ListView):
    model = Booking
    template_name = 'restaraunt/booking.html'
    context_object_name = 'bookings'  
    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all()
        else:
            return self.model.objects.filter(owner=self.request.user)


class BookingCreateView(LoginRequiredMixin,CreateView):
    model = Booking
    template_name = 'restaraunt/booking_create.html'
    success_url = reverse_lazy('booking_list')
    form_class=BookingForm

    def form_valid(self, form):
        try:
            form.instance.owner=self.request.user
            form.is_valid()
            response= super().form_valid(form)  # Call the parent class method to save the form
            return response
        except ValidationError as e:
            error_message = ', '.join(e.messages)
            context = {"errors":error_message,"form":BookingForm(initial={'owner':self.request.user})}

        return render(self.request, "restaraunt/booking_create.html", context)


class BookingUpdateView(UpdateView,AdminRequiredMixin):
    model = Booking
    template_name = 'restaraunt/booking.html'
    fields = ['Name', 'Capacity', 'status']
    success_url = reverse_lazy('booking_list')

class BookingDeleteView(DeleteView,AdminRequiredMixin):
    model = Booking
    template_name = 'restaraunt/confirm_delete.html'
    success_url = reverse_lazy('booking_list')

restaraunt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=device-dpi" />
    <title>DineDesk</title>
    <link rel="icon" type="image/png" href="images/favicon.png">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'restaraunt/css/spacing.css' %}">
    <link rel="stylesheet" href="{% static 'restaraunt/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'restaraunt/css/responsive.css' %}">
{% block title %}{{ section.title }}{% endblock %}
</head>
<body>
 <nav class="navbar navbar-expand-lg main_menu">
        <div class="container">
            <a class="navbar-brand" href="{%url 'index'%}">
                <img src="{% static 'restaraunt/img/DineDesk (4).png' %}"alt="DineDesk" class="img-fluid">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars menu_icon_bar"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav m-auto">
                    <li class="nav-item">
                        <a class="nav-link {%if request.path == '/' or request.path == '/booking/'%} active{%endif%}" aria-current="page" href="{%url 'index'%}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {%if request.path == '/menu'%} active{%endif%}" href="{%url 'menu'%}">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {%if request.path == '/contactus'%} active{%endif%}" href="{%url 'contactus'%}">Contact</a>
                    </li>
                    {% comment %} {%if request.user.is_superuser%}
                    <li class="nav-item">
                        <a class="nav-link {%if request.path == '/tables'%} active{%endif%}" href="{%url 'table_list'%}">Tables</a>
                    </li>
                    {%endif%} {% endcomment %}
                </ul>
                <ul class="menu_icon d-flex flex-wrap sm_p_0">
                    <li class="menu_icon d-flex flex-wrap">
                        {%if user.is_authenticated%}
                            
                            {{request.user}}<a href="{%url 'logout' %}" name="Login"><i class="fas fa-user"></i></a>
                        {% else %}
                        <a href="{%url 'index' %}" name="Login"><i class="fas fa-user"></i></a>
                        
                        {%endif%}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

{% block content %} 
{% endblock %}
 <footer style="background: url(images/footer_bg.jpg);">
        <div class="footer_overlay pt_100 xs_pt_70 pb_100 xs_pb_20">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-lg-5 col-sm-12 col-md-6 ">
                        <div class="tf__footer_content">
                            <a class="footer_logo" href="index.html">
                                <img src="{% static 'restaraunt/img/DineDesk (4).png' %}" alt="DineDesk" class="img-fluid w-100">
                            </a>
                            <span>Discover the essence of India's flavors at our authentic Indian restaurant. Experience culinary excellence, 
                                aromatic spices, and unforgettable dishes. Join us for a remarkable dining adventure.</span>

                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-12 col-md-6">
                        <div class="tf__footer_content">
                            <h3>contact us</h3>
                            <p class="info" style="padding-left: 10px;"> +44 (0) 20 9994 7740</p>
                            <p class="info" style="padding-left: 10px;"> dinedesk@gmail.com</p>
                            <p class="info" style="padding-left: 10px;"> Blackwell Street,Dry Creek,Alaska</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--font-awesome js-->
    <script src="https://kit.fontawesome.com/62613b1ed3.js" crossorigin="anonymous"></script>
    
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    
    
    </body>
    
    
    </html>